# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bootstrap project using Lerna
        run: npx lerna bootstrap
      - name: Run nest-server module tests
        run: |
          cd packages/nest-server
          yarn run test
      - name: Run nest-server e2e tests
        run: |
          cd packages/nest-server
          yarn run test:e2e
      - name: Run schemathesis
        run: |
          cd packages/nest-server
          node ./run-dev.js &
          sleep 60
          docker run --network="host" kiwicom/schemathesis:stable run http://127.0.0.1/api-json --header "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwic3ViIjoxLCJpYXQiOjE1ODQyNjg2OTksImV4cCI6MTU4NDI2ODc1OX0.9FQNp2iVCCP8W1lv950gcXHGSLjrrBw5KW3SVMTxBLA"
          exit